---
title: "mp3_testing"
author: "Nukhbah Majid"
date: "4/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "mp3_trial"
output: html_document
---

```{r}
library(tidyverse)
library(sf)
library(macleish)
library(dplyr)
library(leaflet)
```

```{r}
proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

stream_buffer <- macleish_layers %>%
 pluck("streams") %>%
 st_transform(proj4_aea) %>%
 st_buffer(dist = 60.96) %>% ##200' is 60.96 meter
st_transform(4326)

research_buffer <- macleish_layers %>%
  pluck("research")%>%
  st_transform(proj4_aea)%>%
  st_buffer(dist = 152.4)%>%
  st_transform(4326)

challenge_buffer <- macleish_layers %>%
  pluck("challenge_courses")%>%
  st_transform(proj4_aea)%>%
  st_buffer(dist = 152.4)%>%
  st_transform(4326)

my_points <- tribble(
  ~point, ~lon, ~lat,
  "A", -72.6762800, 42.4539186
)

my_sf <- my_points %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326) 
```

```{r}
new_forest <- macleish_layers%>%
  pluck("forests")

leaflet() %>%
  addTiles() %>%
  addPolygons (data = pluck(macleish_layers, "forests"), weight = 1, popup = ~Sheet1_Ve )%>%
  addPolygons(data = pluck(macleish_layers, "buildings"),
             weight = 1, popup = ~name)

```


```{r}
# this is to try to make a unionized buffer for research and challenge course sites

research_combinedBuff <- st_combine(research_buffer)
challenge_courseBuff <- st_combine(challenge_buffer)
```



```{r}
leaflet() %>%
 addTiles() %>%
 addPolylines(data = pluck(macleish_layers, "trails"), color = "orange", weight = 1) %>%
 addPolylines(data = pluck(macleish_layers, "research"), color = "black", weight = 2) %>%
 addPolygons(data = pluck(macleish_layers, "buildings"),
             weight = 1, popup = ~name) %>%
 addPolylines(data = pluck(macleish_layers, "streams"),
              weight = 1, color = "black") %>%
 addPolylines(data = pluck(macleish_layers, "wetlands"), color = "purple", weight = 2) %>%
 addPolygons(data = stream_buffer) %>%
  addPolygons (data = st_union(research_combinedBuff), color = "red") %>%
  addPolygons (data = st_union(challenge_courseBuff), color = "red") %>%
  addMarkers(data = my_sf, popup = ~point)%>%
  addPolylines(data = pluck(macleish_layers, "contours_3m"), color = "purple", weight = 2)
```

